"""Add scheduling tables

Revision ID: 679c23df944a
Revises: bd8de57a27e2
Create Date: 2025-08-09 08:55:10.451681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679c23df944a'
down_revision: Union[str, None] = 'bd8de57a27e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assessment_data_id'), 'assessment_data', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_types_id'), 'assessment_types', ['id'], unique=False)
    op.drop_index('ix_eligibility_categories_code', table_name='eligibility_categories')
    op.create_index(op.f('ix_eligibility_categories_code'), 'eligibility_categories', ['code'], unique=True)
    op.create_index(op.f('ix_eligibility_categories_id'), 'eligibility_categories', ['id'], unique=False)
    op.create_index(op.f('ix_goal_categories_id'), 'goal_categories', ['id'], unique=False)
    # Skip column comment update due to SQL Server DDL compiler issue
    # op.alter_column('goal_objectives', 'objective_number',
    #            existing_type=sa.INTEGER(),
    #            comment='Objective sequence number (1-10)',
    #            existing_comment='Objective sequence number (1-4)',
    #            existing_nullable=False)
    op.drop_index('ix_goal_objectives_objective_number', table_name='goal_objectives')
    op.create_index(op.f('ix_iep_goals_id'), 'iep_goals', ['id'], unique=False)
    op.create_index(op.f('ix_progress_tracking_id'), 'progress_tracking', ['id'], unique=False)
    op.drop_constraint('FK__progress___goal___69FBBC1F', 'progress_tracking', type_='foreignkey')
    op.create_foreign_key(None, 'progress_tracking', 'iep_goals', ['goal_id'], ['id'])
    op.create_index(op.f('ix_service_information_id'), 'service_information', ['id'], unique=False)
    op.create_index(op.f('ix_service_types_id'), 'service_types', ['id'], unique=False)
    op.create_index(op.f('ix_student_eligibilities_id'), 'student_eligibilities', ['id'], unique=False)
    # Skip column comment update due to SQL Server DDL compiler issue
    # op.alter_column('students', 'school_id',
    #            existing_type=sa.INTEGER(),
    #            comment='Students current school',
    #            existing_nullable=True)
    op.drop_index('ix_students_uic', table_name='students')
    op.create_index(op.f('ix_students_uic'), 'students', ['uic'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_uic'), table_name='students')
    op.create_index('ix_students_uic', 'students', ['uic'], unique=False)
    # Skip column comment update due to SQL Server DDL compiler issue
    # op.alter_column('students', 'school_id',
    #            existing_type=sa.INTEGER(),
    #            comment=None,
    #            existing_comment='Students current school',
    #            existing_nullable=True)
    op.drop_index(op.f('ix_student_eligibilities_id'), table_name='student_eligibilities')
    op.drop_index(op.f('ix_service_types_id'), table_name='service_types')
    op.drop_index(op.f('ix_service_information_id'), table_name='service_information')
    op.drop_constraint(None, 'progress_tracking', type_='foreignkey')
    op.create_foreign_key('FK__progress___goal___69FBBC1F', 'progress_tracking', 'iep_goals', ['goal_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_progress_tracking_id'), table_name='progress_tracking')
    op.drop_index(op.f('ix_iep_goals_id'), table_name='iep_goals')
    op.create_index('ix_goal_objectives_objective_number', 'goal_objectives', ['objective_number'], unique=False)
    # Skip column comment update due to SQL Server DDL compiler issue
    # op.alter_column('goal_objectives', 'objective_number',
    #            existing_type=sa.INTEGER(),
    #            comment='Objective sequence number (1-4)',
    #            existing_comment='Objective sequence number (1-10)',
    #            existing_nullable=False)
    op.drop_index(op.f('ix_goal_categories_id'), table_name='goal_categories')
    op.drop_index(op.f('ix_eligibility_categories_id'), table_name='eligibility_categories')
    op.drop_index(op.f('ix_eligibility_categories_code'), table_name='eligibility_categories')
    op.create_index('ix_eligibility_categories_code', 'eligibility_categories', ['code'], unique=False)
    op.drop_index(op.f('ix_assessment_types_id'), table_name='assessment_types')
    op.drop_index(op.f('ix_assessment_data_id'), table_name='assessment_data')
    # ### end Alembic commands ###
