"""Add therapy session architecture with goals and objectives tracking

Revision ID: 7c26e869115f
Revises: d5797daff9d2
Create Date: 2025-08-09 12:15:54.468819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c26e869115f'
down_revision: Union[str, None] = 'd5797daff9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip column comment updates due to SQL Server DDL compiler issue
    # op.alter_column('goal_objectives', 'objective_number',
    #            existing_type=sa.INTEGER(),
    #            comment='Objective sequence number (1-10)',
    #            existing_comment='Objective sequence number (1-4)',
    #            existing_nullable=False)
    
    # Create therapy_sessions table
    op.create_table('therapy_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('appointment_id', sa.Integer(), nullable=True),
        sa.Column('time_block_id', sa.Integer(), nullable=True),
        sa.Column('session_date', sa.DateTime(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('planned_duration_minutes', sa.Integer(), nullable=True),
        sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
        sa.Column('session_type', sa.String(length=50), server_default='individual', nullable=False),
        sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
        sa.Column('created_from', sa.String(length=50), nullable=True),
        sa.Column('prep_notes', sa.Text(), nullable=True),
        sa.Column('session_notes', sa.Text(), nullable=True),
        sa.Column('therapist_observations', sa.Text(), nullable=True),
        sa.Column('student_engagement', sa.String(length=50), nullable=True),
        sa.Column('materials_used', sa.Text(), nullable=True),
        sa.Column('goals_addressed', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('session_quality', sa.String(length=20), nullable=True),
        sa.Column('follow_up_needed', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('follow_up_notes', sa.Text(), nullable=True),
        sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id']),
        sa.ForeignKeyConstraint(['student_id'], ['students.id']),
        sa.ForeignKeyConstraint(['time_block_id'], ['time_blocks.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_sessions_appointment_id'), 'therapy_sessions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_id'), 'therapy_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_session_date'), 'therapy_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_session_type'), 'therapy_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_status'), 'therapy_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_student_id'), 'therapy_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_time_block_id'), 'therapy_sessions', ['time_block_id'], unique=False)

    # Create session_goals table
    op.create_table('session_goals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('therapy_session_id', sa.Integer(), nullable=False),
        sa.Column('goal_id', sa.Integer(), nullable=False),
        sa.Column('planned', sa.Boolean(), server_default='1', nullable=False),
        sa.Column('worked_on', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('pre_session_notes', sa.Text(), nullable=True),
        sa.Column('session_notes', sa.Text(), nullable=True),
        sa.Column('goal_progress_summary', sa.String(length=500), nullable=True),
        sa.Column('goal_met', sa.Boolean(), nullable=True),
        sa.Column('difficulty_level', sa.String(length=20), nullable=True),
        sa.Column('student_response', sa.String(length=50), nullable=True),
        sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
        sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.ForeignKeyConstraint(['goal_id'], ['iep_goals.id']),
        sa.ForeignKeyConstraint(['therapy_session_id'], ['therapy_sessions.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('therapy_session_id', 'goal_id', name='uq_session_goal')
    )
    op.create_index(op.f('ix_session_goals_goal_id'), 'session_goals', ['goal_id'], unique=False)
    op.create_index(op.f('ix_session_goals_id'), 'session_goals', ['id'], unique=False)
    op.create_index(op.f('ix_session_goals_therapy_session_id'), 'session_goals', ['therapy_session_id'], unique=False)

    # Create session_objectives table
    op.create_table('session_objectives',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('therapy_session_id', sa.Integer(), nullable=False),
        sa.Column('objective_id', sa.Integer(), nullable=False),
        sa.Column('goal_id', sa.Integer(), nullable=False),
        sa.Column('planned', sa.Boolean(), server_default='1', nullable=False),
        sa.Column('worked_on', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('pre_session_notes', sa.Text(), nullable=True),
        sa.Column('session_notes', sa.Text(), nullable=True),
        sa.Column('trials_attempted', sa.Integer(), nullable=True),
        sa.Column('trials_correct', sa.Integer(), nullable=True),
        sa.Column('accuracy_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('independence_level', sa.String(length=50), nullable=True),
        sa.Column('objective_met', sa.Boolean(), nullable=True),
        sa.Column('progress_rating', sa.String(length=20), nullable=True),
        sa.Column('prompt_level', sa.String(length=50), nullable=True),
        sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
        sa.Column('student_engagement', sa.String(length=20), nullable=True),
        sa.Column('data_collection_method', sa.String(length=100), nullable=True),
        sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.ForeignKeyConstraint(['goal_id'], ['iep_goals.id']),
        sa.ForeignKeyConstraint(['objective_id'], ['goal_objectives.id']),
        sa.ForeignKeyConstraint(['therapy_session_id'], ['therapy_sessions.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('therapy_session_id', 'objective_id', name='uq_session_objective')
    )
    op.create_index(op.f('ix_session_objectives_goal_id'), 'session_objectives', ['goal_id'], unique=False)
    op.create_index(op.f('ix_session_objectives_id'), 'session_objectives', ['id'], unique=False)
    op.create_index(op.f('ix_session_objectives_objective_id'), 'session_objectives', ['objective_id'], unique=False)
    op.create_index(op.f('ix_session_objectives_therapy_session_id'), 'session_objectives', ['therapy_session_id'], unique=False)

    # Add therapy_session_id to objective_progress_entries
    op.add_column('objective_progress_entries', sa.Column('therapy_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_objective_progress_entries_therapy_session_id'), 'objective_progress_entries', ['therapy_session_id'], unique=False)
    op.create_foreign_key(None, 'objective_progress_entries', 'therapy_sessions', ['therapy_session_id'], ['id'])
    
    # Skip column comment updates due to SQL Server DDL compiler issue
    # op.alter_column('students', 'school_id',
    #            existing_type=sa.INTEGER(),
    #            comment='Students current school',
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip column comment updates due to SQL Server DDL compiler issue
    # op.alter_column('students', 'school_id',
    #            existing_type=sa.INTEGER(),
    #            comment=None,
    #            existing_comment='Students current school',
    #            existing_nullable=True)
    
    # Remove therapy_session_id from objective_progress_entries
    op.drop_constraint(None, 'objective_progress_entries', type_='foreignkey')
    op.drop_index(op.f('ix_objective_progress_entries_therapy_session_id'), table_name='objective_progress_entries')
    op.drop_column('objective_progress_entries', 'therapy_session_id')
    
    # Drop session_objectives table
    op.drop_index(op.f('ix_session_objectives_therapy_session_id'), table_name='session_objectives')
    op.drop_index(op.f('ix_session_objectives_objective_id'), table_name='session_objectives')
    op.drop_index(op.f('ix_session_objectives_id'), table_name='session_objectives')
    op.drop_index(op.f('ix_session_objectives_goal_id'), table_name='session_objectives')
    op.drop_table('session_objectives')
    
    # Drop session_goals table
    op.drop_index(op.f('ix_session_goals_therapy_session_id'), table_name='session_goals')
    op.drop_index(op.f('ix_session_goals_id'), table_name='session_goals')
    op.drop_index(op.f('ix_session_goals_goal_id'), table_name='session_goals')
    op.drop_table('session_goals')
    
    # Drop therapy_sessions table
    op.drop_index(op.f('ix_therapy_sessions_time_block_id'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_student_id'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_status'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_session_type'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_session_date'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_id'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_appointment_id'), table_name='therapy_sessions')
    op.drop_table('therapy_sessions')
    
    # Skip column comment updates due to SQL Server DDL compiler issue
    # op.alter_column('goal_objectives', 'objective_number',
    #            existing_type=sa.INTEGER(),
    #            comment='Objective sequence number (1-4)',
    #            existing_comment='Objective sequence number (1-10)',
    #            existing_nullable=False)
    # ### end Alembic commands ###
