"""add_datetime_columns_to_activities

Revision ID: 9e22557e19e7
Revises: f6db484bf6a1
Create Date: 2025-09-01 12:23:58.295693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e22557e19e7'
down_revision: Union[str, None] = 'f6db484bf6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_block_activities', sa.Column('start_datetime', sa.DateTime(), nullable=True))
    op.add_column('time_block_activities', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_time_block_activities_start_datetime'), 'time_block_activities', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_time_block_activities_end_datetime'), 'time_block_activities', ['end_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_block_activities_end_datetime'), table_name='time_block_activities')
    op.drop_index(op.f('ix_time_block_activities_start_datetime'), table_name='time_block_activities')
    op.drop_column('time_block_activities', 'end_datetime')
    op.drop_column('time_block_activities', 'start_datetime')
    # ### end Alembic commands ###
