"""add_activity_datetime_and_student_assignments

Revision ID: db148ad4672c
Revises: 9c69ae0cd521
Create Date: 2025-09-01 12:19:24.631227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'db148ad4672c'
down_revision: Union[str, None] = '9c69ae0cd521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_audit_log_operation', table_name='therapy_session_audit_log')
    op.drop_index('IX_audit_log_table_record', table_name='therapy_session_audit_log')
    op.drop_index('IX_audit_log_timestamp', table_name='therapy_session_audit_log')
    op.drop_table('therapy_session_audit_log')
    op.drop_index('ix_students_case_manager', table_name='students')
    op.drop_column('students', 'case_manager')
    op.create_index(op.f('ix_time_block_activities_end_datetime'), 'time_block_activities', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_time_block_activities_start_datetime'), 'time_block_activities', ['start_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_block_activities_start_datetime'), table_name='time_block_activities')
    op.drop_index(op.f('ix_time_block_activities_end_datetime'), table_name='time_block_activities')
    op.add_column('students', sa.Column('case_manager', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.create_index('ix_students_case_manager', 'students', ['case_manager'], unique=False)
    op.create_table('therapy_session_audit_log',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('change_timestamp', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('user_context', sa.NVARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('application_name', sa.NVARCHAR(length=100), server_default=sa.text("('SLPro')"), autoincrement=False, nullable=True),
    sa.Column('database_user', sa.NVARCHAR(length=100), server_default=sa.text('(suser_sname())'), autoincrement=False, nullable=True),
    sa.Column('host_name', sa.NVARCHAR(length=100), server_default=sa.text('(host_name())'), autoincrement=False, nullable=True),
    sa.Column('change_reason', sa.NVARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('session_context', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__therapy___3213E83FC3B6BAE8')
    )
    op.create_index('IX_audit_log_timestamp', 'therapy_session_audit_log', ['change_timestamp'], unique=False)
    op.create_index('IX_audit_log_table_record', 'therapy_session_audit_log', ['table_name', 'record_id'], unique=False)
    op.create_index('IX_audit_log_operation', 'therapy_session_audit_log', ['operation_type'], unique=False)
    # ### end Alembic commands ###
