"""add_missing_activity_columns_and_student_assignments

Revision ID: f6db484bf6a1
Revises: db148ad4672c
Create Date: 2025-09-01 12:23:31.883013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6db484bf6a1'
down_revision: Union[str, None] = 'db148ad4672c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_student_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='assigned', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['time_block_activities.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_student_assignments_activity_id'), 'activity_student_assignments', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_student_assignments_id'), 'activity_student_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_activity_student_assignments_status'), 'activity_student_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_activity_student_assignments_student_id'), 'activity_student_assignments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_student_assignments_student_id'), table_name='activity_student_assignments')
    op.drop_index(op.f('ix_activity_student_assignments_status'), table_name='activity_student_assignments')
    op.drop_index(op.f('ix_activity_student_assignments_id'), table_name='activity_student_assignments')
    op.drop_index(op.f('ix_activity_student_assignments_activity_id'), table_name='activity_student_assignments')
    op.drop_table('activity_student_assignments')
    # ### end Alembic commands ###
