#!/usr/bin/env python3
"""Fill a development database with believable, entirely fake caseload data.

Nothing in here comes from production. Every name, date of birth, UIC, goal,
objective and progress note is generated by Faker from a fixed seed, so two
runs produce the same caseload and a diff of the seeded data is meaningful.

HARD GUARD
----------
This script writes. It refuses to run unless the target is either

  * a database literally named ``slpdb_dev`` (asked of the SERVER via
    ``SELECT DB_NAME()``, never taken from the caller's argument), or
  * a sqlite file -- the local/test dialect, which by construction cannot be
    one of the Azure databases.

There is no flag, environment variable or argument that turns the guard off.
``slpdb_2`` is production and holds real student PII; it is not a seed target
and never will be.

Usage
-----
    # local scratch database (sqlite)
    python backend/scripts/seed_dev.py --sqlite ./dev-seed.db --reset

    # Azure dev database (Entra token auth via the az CLI)
    SLP_DB_NAME=slpdb_dev python backend/scripts/seed_dev.py --reset

``--reset`` deletes the rows this script created, in foreign-key order, before
re-seeding. Without it, a second run stops rather than colliding with the
unique constraints on ``students.student_alias`` / ``students.uic``.

Only the tables this script seeds are cleared. If some other tool has put rows
into a table that references ``students`` (``progress_tracking``,
``ai_chat_sessions``, ...), ``--reset`` will fail on the foreign key rather
than silently widen its blast radius -- clear those yourself first.
"""

from __future__ import annotations

import argparse
import os
import random
import sys
import warnings
from datetime import date, datetime, time, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

#: The only SQL Server database name this script will write to.
ALLOWED_DB_NAME = "slpdb_dev"

#: Deterministic output: same seed, same caseload, every run.
RANDOM_SEED = 20260819

#: The external auth id the backend's anonymous-fallback path uses in
#: development (settings.auth_fallback_user_external_id). Seeding a user with
#: this id is what makes a local run land on a populated caseload instead of an
#: empty one.
DEV_USER_EXTERNAL_ID = "local-user"

#: How many rows of each table a full seed produces. The test asserts against
#: this, so a change in the generator that silently changes the shape of the
#: dataset fails rather than drifting.
PLAN: Dict[str, int] = {
    "schools": 3,
    "teachers": 10,
    "roles": 3,
    "teacher_roles": 10,
    "teacher_school_assignments": 10,
    "eligibility_categories": 6,
    "goal_categories": 6,
    "students": 25,
    "student_teacher_assignments": 25,
    "student_eligibilities": 35,
    "iep_goals": 50,
    "goal_objectives": 150,
    "time_blocks": 6,
    "block_assignments": 24,
    "appointments": 100,
    "therapy_sessions": 50,
    "session_goals": 100,
    "session_objectives": 100,
    "objective_progress_entries": 100,
    "users": 1,
    "user_student_access": 25,
}

GOALS_PER_STUDENT = 2
OBJECTIVES_PER_GOAL = 3
APPOINTMENTS_PER_STUDENT = 4
PAST_APPOINTMENTS_PER_STUDENT = 2
STUDENTS_PER_BLOCK = 4


class GuardViolation(RuntimeError):
    """Raised when a seed was attempted against something that is not dev."""


# ---------------------------------------------------------------------------
# the guard
# ---------------------------------------------------------------------------


def assert_seedable(connection) -> str:
    """Return a description of the target, or raise.

    Takes a live connection rather than a URL on purpose: the SQL Server branch
    asks the server which database it actually landed in. A typo in
    ``SLP_DB_NAME``, a stale environment variable, or a connection string that
    resolves somewhere unexpected all fail here rather than after the first
    INSERT.
    """
    dialect = connection.dialect.name

    if dialect == "sqlite":
        return "sqlite"

    if dialect != "mssql":
        raise GuardViolation(
            f"refusing to seed a {dialect!r} database: this script only ever writes to "
            f"sqlite or to the SQL Server database named {ALLOWED_DB_NAME!r}."
        )

    from sqlalchemy import text

    name = connection.execute(text("SELECT DB_NAME()")).scalar_one()
    if name != ALLOWED_DB_NAME:
        raise GuardViolation(
            f"refusing to seed {name!r}. This script writes fake data and only ever "
            f"targets {ALLOWED_DB_NAME!r}. (slpdb_2 is PRODUCTION.)"
        )
    return str(name)


# ---------------------------------------------------------------------------
# engines
# ---------------------------------------------------------------------------

_SQLITE_SHIM_INSTALLED = False


def _install_sqlite_shim() -> None:
    """Turn foreign-key enforcement on for sqlite connections.

    This used to also rewrite ``GETDATE()`` to ``CURRENT_TIMESTAMP`` in outgoing
    DDL, because the models hard-coded the SQL-Server-only
    ``server_default=text("GETDATE()")``. They now use ``func.now()``, which the
    sqlite dialect renders as ``CURRENT_TIMESTAMP`` on its own, so only the
    pragma is left.
    """
    global _SQLITE_SHIM_INSTALLED
    if _SQLITE_SHIM_INSTALLED:
        return

    from sqlalchemy import event
    from sqlalchemy.engine import Engine

    @event.listens_for(Engine, "connect")
    def _fk_pragma(dbapi_connection, connection_record):  # noqa: ANN001
        # Foreign keys are OFF by default in sqlite. Turning them on is what
        # makes the local run a real test of the insert/delete ordering.
        try:
            cursor = dbapi_connection.cursor()
            cursor.execute("PRAGMA foreign_keys=ON")
            cursor.close()
        except Exception:  # pragma: no cover - not a sqlite connection
            pass

    _SQLITE_SHIM_INSTALLED = True


def build_sqlite_engine(path: str):
    from sqlalchemy import create_engine

    _install_sqlite_shim()
    if path in (":memory:", "memory"):
        url = "sqlite://"
    else:
        url = f"sqlite:///{Path(path).resolve().as_posix()}"
    return create_engine(url, future=True)


def build_azure_engine(server: str, database: str, driver: str, auth: str):
    """Entra-token connection to Azure SQL, identical to provision_dev_db.py."""
    import provision_dev_db as provision

    return provision.build_engine(server, database, driver=driver, auth=auth)


def _resolve_engine(args: argparse.Namespace):
    if args.sqlite:
        return build_sqlite_engine(args.sqlite)

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    server = args.server or os.environ.get("SLP_DB_SERVER") or "hortonfam.database.windows.net"
    database = args.database or os.environ.get("SLP_DB_NAME") or ""
    if not database:
        raise SystemExit(
            "SLP_DB_NAME (or --database, or --sqlite PATH) is required -- "
            "refusing to guess a database name."
        )
    if database != ALLOWED_DB_NAME:
        raise GuardViolation(
            f"this script only ever seeds {ALLOWED_DB_NAME!r}; SLP_DB_NAME is {database!r}."
        )
    return build_azure_engine(server, database, args.driver, args.auth)


# ---------------------------------------------------------------------------
# reference data
# ---------------------------------------------------------------------------

ELIGIBILITY_CATEGORIES: Sequence[Dict[str, Any]] = (
    {"name": "Speech and Language Impairment", "code": "SLI", "display_order": 1},
    {"name": "Specific Learning Disability", "code": "SLD", "display_order": 2},
    {"name": "Autism Spectrum Disorder", "code": "ASD", "display_order": 3},
    {"name": "Other Health Impairment", "code": "OHI", "display_order": 4},
    {"name": "Developmental Delay", "code": "DD", "display_order": 5},
    {"name": "Hearing Impairment", "code": "HI", "display_order": 6},
)

GOAL_CATEGORIES: Sequence[Dict[str, str]] = (
    {"name": "Articulation", "description": "Production of individual speech sounds"},
    {"name": "Language", "description": "Receptive and expressive language"},
    {"name": "Fluency", "description": "Rate, rhythm and continuity of speech"},
    {"name": "Voice", "description": "Pitch, loudness and vocal quality"},
    {"name": "Pragmatics", "description": "Social use of language"},
    {"name": "Literacy", "description": "Phonological awareness and reading support"},
)

ROLE_NAMES: Sequence[str] = ("General Education Teacher", "Special Education Teacher", "Case Manager")

GRADE_LEVELS: Sequence[str] = ("K", "1", "2", "3", "4", "5", "6", "7", "8")

GOAL_TEMPLATES: Dict[str, Dict[str, str]] = {
    "Articulation": {
        "goal": "produce the target phoneme in all word positions at the conversational level",
        "target": "with 80% accuracy across 3 consecutive therapy sessions",
        "objectives": (
            "produce the target phoneme in isolation and in syllables",
            "produce the target phoneme in single words in all positions",
            "produce the target phoneme in structured sentences and short narratives",
        ),
    },
    "Language": {
        "goal": "use grade-level vocabulary and complete grammatical sentences in structured tasks",
        "target": "in 4 of 5 opportunities across 3 consecutive data collection days",
        "objectives": (
            "answer wh- questions about a short passage",
            "use conjunctions to combine two related ideas",
            "retell a short story including character, setting and problem",
        ),
    },
    "Fluency": {
        "goal": "use learned fluency-shaping strategies during structured conversation",
        "target": "with fewer than 5% disfluent syllables across 3 sessions",
        "objectives": (
            "identify moments of disfluency in recorded speech",
            "apply easy onset and light contact at the phrase level",
            "self-monitor and repair disfluencies in conversation",
        ),
    },
    "Voice": {
        "goal": "use easy, resonant voice production during classroom-length speaking tasks",
        "target": "with no more than 2 clinician cues per 10-minute sample",
        "objectives": (
            "demonstrate diaphragmatic breathing during sustained phonation",
            "produce phrases at a comfortable pitch and loudness",
            "carry easy voice into a five-minute conversational sample",
        ),
    },
    "Pragmatics": {
        "goal": "initiate and maintain a reciprocal conversation with a peer",
        "target": "for 4 conversational turns in 4 of 5 opportunities",
        "objectives": (
            "identify appropriate conversational openers for a given setting",
            "maintain topic across three conversational turns",
            "recognise and respond to a partner's nonverbal cues",
        ),
    },
    "Literacy": {
        "goal": "demonstrate phonological awareness skills that support decoding",
        "target": "with 85% accuracy on curriculum-based probes",
        "objectives": (
            "segment single-syllable words into individual phonemes",
            "blend three to four phonemes into a spoken word",
            "manipulate initial and final phonemes to make new words",
        ),
    },
}

PROGRESS_RATINGS = ("Emerging", "Progressing", "Making steady progress", "Approaching mastery", "Mastered")
INDEPENDENCE_LEVELS = ("maximal support", "moderate support", "minimal support", "independent")
PROMPT_LEVELS = ("verbal model", "phonemic cue", "visual cue", "indirect verbal", "no prompt")
ENGAGEMENT = ("engaged", "highly engaged", "variable", "reluctant at first")
SESSION_TYPES = ("individual", "group")
BLOCK_TITLES = (
    "Morning articulation group",
    "Early language block",
    "Fluency support block",
    "Afternoon language group",
    "Social communication block",
    "Literacy support block",
)


# ---------------------------------------------------------------------------
# generation
# ---------------------------------------------------------------------------


def _school_year_start(today: date) -> date:
    """1 September of the current school year."""
    return date(today.year if today.month >= 9 else today.year - 1, 9, 1)


def _weekday_at(anchor: date, offset_days: int, hour: int, minute: int) -> datetime:
    """A datetime *offset_days* from *anchor*, nudged off Saturday/Sunday."""
    day = anchor + timedelta(days=offset_days)
    while day.weekday() >= 5:
        day += timedelta(days=1)
    return datetime.combine(day, time(hour=hour, minute=minute))


def _progress_note(first: str, last: str, category: str, objective: str, rng: random.Random) -> str:
    """A note that reads like one, with the student's name inside sentences."""
    accuracy = rng.randrange(55, 96)
    trials = rng.choice((10, 15, 20, 25))
    correct = max(1, round(trials * accuracy / 100))
    prompt = rng.choice(PROMPT_LEVELS)
    engagement = rng.choice(ENGAGEMENT)
    return (
        f"{first} worked on {category.lower()} targets this session and was {engagement} throughout. "
        f"Across {trials} structured trials {first} was accurate on {correct} ({accuracy}%) while "
        f"working to {objective}. {first} needed a {prompt} on the harder items, and by the end of "
        f"the session {first} {last[0]}. was self-correcting without clinician support on the easier "
        f"set. Plan: continue at this level next session and probe carryover into conversation."
    )


def seed(session, *, verbose: bool = True) -> Dict[str, int]:
    """Insert the whole fake caseload, in foreign-key order. Returns row counts."""
    from faker import Faker

    from app.models.activity_student_assignment import ActivityStudentAssignment  # noqa: F401
    from app.models.appointment import Appointment
    from app.models.block_assignment import BlockAssignment
    from app.models.eligibility_category import EligibilityCategory
    from app.models.goal_category import GoalCategory
    from app.models.goal_objective import GoalObjective
    from app.models.iep_goal import IEPGoal
    from app.models.objective_progress_entry import ObjectiveProgressEntry
    from app.models.role import Role
    from app.models.school import School
    from app.models.session_goal import SessionGoal
    from app.models.session_objective import SessionObjective
    from app.models.student import Student
    from app.models.student_eligibility import StudentEligibility
    from app.models.student_teacher_assignment import StudentTeacherAssignment
    from app.models.teacher import Teacher
    from app.models.teacher_role import TeacherRole
    from app.models.teacher_school_assignment import TeacherSchoolAssignment
    from app.models.therapy_session import TherapySession
    from app.models.time_block import TimeBlock
    from app.models.user import User
    from app.models.user_student_access import UserStudentAccess

    fake = Faker("en_US")
    Faker.seed(RANDOM_SEED)
    rng = random.Random(RANDOM_SEED)

    today = date.today()
    year_start = _school_year_start(today)
    counts: Dict[str, int] = {}

    def log(message: str) -> None:
        if verbose:
            print(message)

    # -- 1. schools ---------------------------------------------------------
    schools: List[School] = []
    for i in range(PLAN["schools"]):
        city = fake.city()
        schools.append(
            School(
                name=f"{city} {('Elementary', 'Middle', 'Intermediate')[i % 3]} School",
                address=fake.street_address(),
                phone=fake.numerify("###-###-####"),
                email=f"office{i + 1}@example-district.invalid",
                district="Example Public Schools",
                principal_name=fake.name(),
                contact_person=fake.name(),
                contact_phone=fake.numerify("###-###-####"),
                notes="Fake school record created by seed_dev.py.",
                is_active=True,
            )
        )
    session.add_all(schools)
    session.flush()
    counts["schools"] = len(schools)

    # -- 2. roles -----------------------------------------------------------
    roles = [Role(name=name, is_active=True) for name in ROLE_NAMES]
    session.add_all(roles)
    session.flush()
    counts["roles"] = len(roles)

    # -- 3. teachers --------------------------------------------------------
    teachers: List[Teacher] = []
    for i in range(PLAN["teachers"]):
        first, last = fake.first_name(), fake.last_name()
        teachers.append(
            Teacher(
                first_name=first,
                last_name=last,
                email=f"{first.lower()}.{last.lower()}{i}@example-district.invalid",
                phone=fake.numerify("###-###-####"),
                title=rng.choice(("Ms.", "Mr.", "Mrs.", "Dr.")),
                department=rng.choice(("General Education", "Special Education", "Related Services")),
                room_number=f"{rng.randrange(100, 320)}",
                preferred_contact_method=rng.choice(("email", "phone")),
                notes="Fake teacher record created by seed_dev.py.",
                is_active=True,
            )
        )
    session.add_all(teachers)
    session.flush()
    counts["teachers"] = len(teachers)

    session.add_all(
        [TeacherRole(teacher_id=t.id, role_id=roles[i % len(roles)].id) for i, t in enumerate(teachers)]
    )
    counts["teacher_roles"] = len(teachers)

    session.add_all(
        [
            TeacherSchoolAssignment(
                teacher_id=t.id,
                school_id=schools[i % len(schools)].id,
                start_date=year_start,
                end_date=None,
                is_primary=True,
                notes=None,
            )
            for i, t in enumerate(teachers)
        ]
    )
    counts["teacher_school_assignments"] = len(teachers)

    # -- 4. reference tables ------------------------------------------------
    eligibility_categories = [
        EligibilityCategory(
            name=spec["name"],
            code=spec["code"],
            description=f"{spec['name']} ({spec['code']}) -- seeded reference row.",
            is_active=True,
            display_order=spec["display_order"],
        )
        for spec in ELIGIBILITY_CATEGORIES
    ]
    session.add_all(eligibility_categories)

    goal_categories = [
        GoalCategory(name=spec["name"], description=spec["description"], is_active=True)
        for spec in GOAL_CATEGORIES
    ]
    session.add_all(goal_categories)
    session.flush()
    counts["eligibility_categories"] = len(eligibility_categories)
    counts["goal_categories"] = len(goal_categories)

    # -- 5. students --------------------------------------------------------
    students: List[Student] = []
    for i in range(PLAN["students"]):
        first, last = fake.first_name(), fake.last_name()
        dob = fake.date_of_birth(minimum_age=5, maximum_age=14)
        iep_date = year_start + timedelta(days=rng.randrange(0, 120))
        students.append(
            Student(
                student_alias=f"{first.lower()}-{last.lower()}-{i + 1:03d}"[:64],
                first=first,
                last=last,
                uic=fake.unique.numerify("##########"),
                grade_level=GRADE_LEVELS[i % len(GRADE_LEVELS)],
                enrollment_status="Active",
                is_archived=False,
                date_of_birth=dob,
                iep_date=iep_date,
                annual_review_due_date=iep_date + timedelta(days=365),
                reevaluation_due_date=iep_date + timedelta(days=365 * 3),
                iep_meeting_date=iep_date,
                initial_evaluation_date=iep_date - timedelta(days=rng.randrange(200, 900)),
                eligibility_determination_date=iep_date - timedelta(days=rng.randrange(1, 30)),
                school_id=schools[i % len(schools)].id,
                teacher_id=teachers[i % len(teachers)].id,
                case_manager_id=teachers[(i + 3) % len(teachers)].id,
            )
        )
    session.add_all(students)
    session.flush()
    counts["students"] = len(students)

    session.add_all(
        [
            StudentTeacherAssignment(
                student_id=s.id,
                teacher_id=teachers[i % len(teachers)].id,
                subject=rng.choice(("Homeroom", "English Language Arts", "Mathematics", "Resource")),
                start_date=year_start,
                end_date=None,
                is_primary=True,
            )
            for i, s in enumerate(students)
        ]
    )
    counts["student_teacher_assignments"] = len(students)

    # -- 6. eligibilities ---------------------------------------------------
    eligibilities: List[StudentEligibility] = []
    for i, student in enumerate(students):
        primary = eligibility_categories[0]  # everyone on an SLP caseload is SLI
        eligibilities.append(
            StudentEligibility(
                student_id=student.id,
                eligibility_category_id=primary.id,
                start_date=student.eligibility_determination_date or year_start,
                end_date=None,
                is_primary=True,
                notes=f"Primary eligibility for {student.first} {student.last}.",
            )
        )
        if i < 10:
            secondary = eligibility_categories[1 + (i % (len(eligibility_categories) - 1))]
            eligibilities.append(
                StudentEligibility(
                    student_id=student.id,
                    eligibility_category_id=secondary.id,
                    start_date=student.eligibility_determination_date or year_start,
                    end_date=None,
                    is_primary=False,
                    notes=f"Secondary eligibility for {student.first} {student.last}.",
                )
            )
    session.add_all(eligibilities)
    counts["student_eligibilities"] = len(eligibilities)

    # -- 7. goals and objectives -------------------------------------------
    goals: List[IEPGoal] = []
    goals_by_student: Dict[int, List[IEPGoal]] = {}
    for i, student in enumerate(students):
        for g in range(GOALS_PER_STUDENT):
            category = goal_categories[(i + g) % len(goal_categories)]
            template = GOAL_TEMPLATES[category.name]
            goal = IEPGoal(
                student_id=student.id,
                goal_category_id=category.id,
                goal_number=f"{g + 1}",
                goal_description=(
                    f"By the next annual review, {student.first} will {template['goal']} "
                    f"{template['target']}."
                ),
                target_behavior=template["goal"].capitalize() + ".",
                baseline_data=(
                    f"{student.first} performed at {rng.randrange(20, 55)}% accuracy on the "
                    f"baseline probe administered {(year_start + timedelta(days=5)).isoformat()}."
                ),
                target_criteria=template["target"].capitalize() + ".",
                goal_status="Active",
                start_date=student.iep_date or year_start,
                end_date=(student.iep_date or year_start) + timedelta(days=365),
            )
            goals.append(goal)
            goals_by_student.setdefault(student.id, []).append(goal)
    session.add_all(goals)
    session.flush()
    counts["iep_goals"] = len(goals)

    objectives: List[GoalObjective] = []
    objectives_by_goal: Dict[int, List[GoalObjective]] = {}
    for goal in goals:
        category_name = next(c.name for c in goal_categories if c.id == goal.goal_category_id)
        template = GOAL_TEMPLATES[category_name]
        for n in range(OBJECTIVES_PER_GOAL):
            objective = GoalObjective(
                goal_id=goal.id,
                objective_number=n + 1,
                objective_description=(
                    f"Given structured practice, the student will {template['objectives'][n]}."
                ),
                progress_status=rng.choice(PROGRESS_RATINGS[:4]),
                schedule_frequency=rng.choice(("Weekly", "Twice weekly", "Every other week")),
            )
            objectives.append(objective)
            objectives_by_goal.setdefault(goal.id, []).append(objective)
    session.add_all(objectives)
    session.flush()
    counts["goal_objectives"] = len(objectives)

    # -- 8. time blocks and block assignments -------------------------------
    time_blocks: List[TimeBlock] = []
    for i in range(PLAN["time_blocks"]):
        start = _weekday_at(today, -(i * 7) - 1, 9 + (i % 4), 0)
        time_blocks.append(
            TimeBlock(
                teacher_id=teachers[i % len(teachers)].id,
                school_id=schools[i % len(schools)].id,
                start_datetime=start,
                end_datetime=start + timedelta(minutes=45),
                block_type="group_therapy",
                title=BLOCK_TITLES[i],
                max_students=STUDENTS_PER_BLOCK + 2,
                location=f"Speech room {100 + i}",
                notes="Fake time block created by seed_dev.py.",
                am_pm_indicator="AM" if start.hour < 12 else "PM",
                status="active",
                created_by=DEV_USER_EXTERNAL_ID,
            )
        )
    session.add_all(time_blocks)
    session.flush()
    counts["time_blocks"] = len(time_blocks)

    block_assignments: List[BlockAssignment] = []
    for i, block in enumerate(time_blocks):
        for student in students[i * STUDENTS_PER_BLOCK: (i + 1) * STUDENTS_PER_BLOCK]:
            block_assignments.append(
                BlockAssignment(
                    time_block_id=block.id,
                    student_id=student.id,
                    status="assigned",
                    created_by=DEV_USER_EXTERNAL_ID,
                )
            )
    session.add_all(block_assignments)
    counts["block_assignments"] = len(block_assignments)

    # -- 9. appointments ----------------------------------------------------
    appointments: List[Appointment] = []
    appointments_by_student: Dict[int, List[Appointment]] = {}
    for i, student in enumerate(students):
        for a in range(APPOINTMENTS_PER_STUDENT):
            # First PAST_APPOINTMENTS_PER_STUDENT are in the past (they get a
            # completed therapy session); the rest are still on the calendar.
            past = a < PAST_APPOINTMENTS_PER_STUDENT
            offset = -(7 * (PAST_APPOINTMENTS_PER_STUDENT - a)) if past else 3 + 7 * (a - PAST_APPOINTMENTS_PER_STUDENT)
            start = _weekday_at(today, offset, 8 + (i % 6), (a % 2) * 30)
            appointment = Appointment(
                student_id=student.id,
                teacher_id=teachers[i % len(teachers)].id,
                school_id=student.school_id,
                time_block_id=time_blocks[i % len(time_blocks)].id if a == 0 else None,
                start_datetime=start,
                end_datetime=start + timedelta(minutes=30),
                appointment_type="group" if a == 0 else "individual",
                status="completed" if past else "scheduled",
                location=f"Speech room {100 + (i % 6)}",
                notes=f"Scheduled speech-language session for {student.first} {student.last}.",
                therapy_session_completed=past,
                created_by=DEV_USER_EXTERNAL_ID,
            )
            appointments.append(appointment)
            appointments_by_student.setdefault(student.id, []).append(appointment)
    session.add_all(appointments)
    session.flush()
    counts["appointments"] = len(appointments)

    # -- 10. therapy sessions ----------------------------------------------
    sessions: List[TherapySession] = []
    for student in students:
        for appointment in appointments_by_student[student.id][:PAST_APPOINTMENTS_PER_STUDENT]:
            sessions.append(
                TherapySession(
                    student_id=student.id,
                    appointment_id=appointment.id,
                    time_block_id=appointment.time_block_id,
                    session_date=appointment.start_datetime,
                    start_time=appointment.start_datetime,
                    end_time=appointment.end_datetime,
                    actual_start_time=appointment.start_datetime + timedelta(minutes=2),
                    actual_end_time=appointment.end_datetime - timedelta(minutes=1),
                    planned_duration_minutes=30,
                    actual_duration_minutes=27,
                    session_type="group" if appointment.time_block_id else "individual",
                    status="completed",
                    created_from="appointment",
                    prep_notes=f"Materials pulled for {student.first}: picture cards and a self-rating chart.",
                    session_notes=(
                        f"{student.first} arrived on time and settled quickly. Targets were probed at the "
                        f"word and sentence level, and {student.first} tracked their own accuracy on the "
                        f"chart. Carryover homework was sent home with {student.first} {student.last[0]}."
                    ),
                    therapist_observations=(
                        f"{student.first} responded best to visual cues; fading them mid-session held up."
                    ),
                    student_engagement=rng.choice(ENGAGEMENT),
                    materials_used="Picture cards, self-rating chart, mirror",
                    goals_addressed=True,
                    session_quality=rng.choice(("good", "excellent", "fair")),
                    follow_up_needed=rng.random() < 0.25,
                    created_by=DEV_USER_EXTERNAL_ID,
                )
            )
    session.add_all(sessions)
    session.flush()
    counts["therapy_sessions"] = len(sessions)

    # -- 11. session goals / objectives / progress entries ------------------
    session_goals: List[SessionGoal] = []
    session_objectives: List[SessionObjective] = []
    progress_entries: List[ObjectiveProgressEntry] = []

    students_by_id = {s.id: s for s in students}
    category_names = {c.id: c.name for c in goal_categories}

    for therapy in sessions:
        student = students_by_id[therapy.student_id]
        initials = f"{student.first[0]}{student.last[0]}".upper()
        for goal in goals_by_student[student.id]:
            session_goals.append(
                SessionGoal(
                    therapy_session_id=therapy.id,
                    goal_id=goal.id,
                    planned=True,
                    worked_on=True,
                    priority=int(goal.goal_number or 1),
                    pre_session_notes=f"Warm up {student.first} on the previous session's target set.",
                    session_notes=(
                        f"{student.first} worked this goal for roughly 12 minutes and needed fewer cues "
                        f"than last week."
                    ),
                    goal_progress_summary=rng.choice(PROGRESS_RATINGS),
                    goal_met=rng.random() < 0.4,
                    difficulty_level=rng.choice(("easy", "moderate", "hard")),
                    student_response=rng.choice(("engaged", "motivated", "distracted")),
                    time_spent_minutes=rng.choice((10, 12, 15)),
                )
            )

            objective = objectives_by_goal[goal.id][0]
            trials = rng.choice((10, 15, 20))
            correct = rng.randrange(max(1, trials // 2), trials + 1)
            accuracy = round(correct / trials * 100, 2)
            category = category_names[goal.goal_category_id]

            session_objectives.append(
                SessionObjective(
                    therapy_session_id=therapy.id,
                    objective_id=objective.id,
                    goal_id=goal.id,
                    planned=True,
                    worked_on=True,
                    priority=1,
                    pre_session_notes=f"Probe {student.first} at the level reached last session.",
                    session_notes=(
                        f"{student.first} completed {correct} of {trials} trials correctly ({accuracy}%)."
                    ),
                    trials_attempted=trials,
                    trials_correct=correct,
                    accuracy_percentage=accuracy,
                    independence_level=rng.choice(INDEPENDENCE_LEVELS),
                    objective_met=accuracy >= 80,
                    progress_rating=rng.choice(("minimal", "steady", "strong")),
                    prompt_level=rng.choice(PROMPT_LEVELS),
                    time_spent_minutes=rng.choice((8, 10, 12)),
                    student_engagement=rng.choice(("high", "medium", "low")),
                    data_collection_method="trial-by-trial tally",
                )
            )

            progress_entries.append(
                ObjectiveProgressEntry(
                    objective_id=objective.id,
                    therapy_session_id=therapy.id,
                    progress_date=therapy.session_date.date(),
                    progress_on_objective=rng.choice(PROGRESS_RATINGS),
                    progress_comments=_progress_note(
                        student.first,
                        student.last,
                        category,
                        objective.objective_description.rstrip(".").split("will ", 1)[-1],
                        rng,
                    ),
                    therapist_initials=initials,
                    session_type=rng.choice(SESSION_TYPES),
                )
            )

    session.add_all(session_goals)
    session.add_all(session_objectives)
    session.add_all(progress_entries)
    counts["session_goals"] = len(session_goals)
    counts["session_objectives"] = len(session_objectives)
    counts["objective_progress_entries"] = len(progress_entries)

    # -- 12. the dev user and its access grants -----------------------------
    dev_user = User(
        external_auth_id=DEV_USER_EXTERNAL_ID,
        email="dev@example-district.invalid",
        display_name="Local Dev User",
        role="admin",
        is_active=True,
    )
    session.add(dev_user)
    session.flush()
    counts["users"] = 1

    session.add_all(
        [
            UserStudentAccess(
                user_id=dev_user.id,
                student_id=student.id,
                granted_by_user_id=dev_user.id,
                is_active=True,
            )
            for student in students
        ]
    )
    counts["user_student_access"] = len(students)

    session.commit()
    log(f"seeded {sum(counts.values())} rows across {len(counts)} tables")
    return counts


# ---------------------------------------------------------------------------
# reset
# ---------------------------------------------------------------------------

#: Reverse foreign-key order. Anything added to seed() has to be added here.
DELETE_ORDER: Sequence[str] = (
    "user_student_access",
    "users",
    "objective_progress_entries",
    "session_objectives",
    "session_goals",
    "therapy_sessions",
    "appointments",
    "block_assignments",
    "time_blocks",
    "goal_objectives",
    "iep_goals",
    "student_eligibilities",
    "student_teacher_assignments",
    "students",
    "teacher_school_assignments",
    "teacher_roles",
    "roles",
    "teachers",
    "schools",
    "goal_categories",
    "eligibility_categories",
)


def _model_by_table() -> Dict[str, Any]:
    import app.models  # noqa: F401
    from app.db.base import Base

    return {mapper.class_.__tablename__: mapper.class_ for mapper in Base.registry.mappers}


def reset(session, *, verbose: bool = True) -> Dict[str, int]:
    """Delete every row this script creates, in foreign-key order."""
    from sqlalchemy import delete

    models = _model_by_table()
    deleted: Dict[str, int] = {}
    for table in DELETE_ORDER:
        model = models[table]
        result = session.execute(delete(model))
        deleted[table] = result.rowcount or 0
        if verbose and deleted[table]:
            print(f"  - {table}: {deleted[table]} row(s)")
    session.commit()
    if verbose:
        print(f"reset removed {sum(deleted.values())} row(s)")
    return deleted


def count_rows(session) -> Dict[str, int]:
    from sqlalchemy import func, select

    models = _model_by_table()
    return {
        table: session.execute(select(func.count()).select_from(models[table])).scalar_one()
        for table in PLAN
    }


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def run(engine, *, do_reset: bool, verbose: bool = True) -> Dict[str, int]:
    """Guard, ensure the schema exists, optionally reset, then seed."""
    from sqlalchemy.orm import Session

    import app.models  # noqa: F401
    from app.db.base import Base

    with engine.connect() as connection:
        target = assert_seedable(connection)
    if verbose:
        print(f"target: {target} -- guard satisfied")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        Base.metadata.create_all(engine)

    with Session(engine) as session:
        if do_reset:
            if verbose:
                print("--reset: deleting seeded rows in foreign-key order")
            reset(session, verbose=verbose)
        else:
            existing = count_rows(session)
            populated = {t: n for t, n in existing.items() if n}
            if populated:
                raise SystemExit(
                    "refusing to seed on top of existing rows: "
                    + ", ".join(f"{t}={n}" for t, n in sorted(populated.items()))
                    + "\nRe-run with --reset to clear them first."
                )
        counts = seed(session, verbose=verbose)

    return counts


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="seed_dev.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--sqlite", default=None, help="seed a local sqlite file instead of Azure SQL")
    parser.add_argument("--server", default=None, help="default: $SLP_DB_SERVER")
    parser.add_argument("--database", default=None, help=f"default: $SLP_DB_NAME (must be {ALLOWED_DB_NAME})")
    parser.add_argument(
        "--driver",
        default=os.environ.get("SLP_ODBC_DRIVER", "ODBC Driver 18 for SQL Server"),
        help="ODBC driver name",
    )
    parser.add_argument("--auth", choices=("token", "azcli"), default=os.environ.get("SLP_DB_AUTH", "token"))
    parser.add_argument("--reset", action="store_true", help="delete the seeded rows first (re-runnable)")
    parser.add_argument("--quiet", action="store_true", help="only print the final summary line")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    verbose = not args.quiet
    try:
        engine = _resolve_engine(args)
        counts = run(engine, do_reset=args.reset, verbose=verbose)
    except GuardViolation as exc:
        print(f"GUARD: {exc}", file=sys.stderr)
        return 2
    for table in PLAN:
        got = counts.get(table, 0)
        flag = "" if got == PLAN[table] else f"   (plan says {PLAN[table]})"
        print(f"  {table:<32} {got:>5}{flag}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
