"""add_time_block_enhancements_and_activities

Revision ID: 7807dc6ddd5b
Revises: d03f74cdd490
Create Date: 2025-08-10 13:13:40.239714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7807dc6ddd5b'
down_revision: Union[str, None] = 'd03f74cdd490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_block_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_block_id', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='5', nullable=False),
    sa.Column('activity_name', sa.String(length=200), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('materials_needed', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['time_block_id'], ['time_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_block_activities_id'), 'time_block_activities', ['id'], unique=False)
    op.create_index(op.f('ix_time_block_activities_sequence_order'), 'time_block_activities', ['sequence_order'], unique=False)
    op.create_index(op.f('ix_time_block_activities_time_block_id'), 'time_block_activities', ['time_block_id'], unique=False)
    op.add_column('appointments', sa.Column('time_block_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_appointments_time_block_id'), 'appointments', ['time_block_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'time_blocks', ['time_block_id'], ['id'])
    op.add_column('time_blocks', sa.Column('am_pm_indicator', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_time_blocks_am_pm_indicator'), 'time_blocks', ['am_pm_indicator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_blocks_am_pm_indicator'), table_name='time_blocks')
    op.drop_column('time_blocks', 'am_pm_indicator')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_time_block_id'), table_name='appointments')
    op.drop_column('appointments', 'time_block_id')
    op.drop_index(op.f('ix_time_block_activities_time_block_id'), table_name='time_block_activities')
    op.drop_index(op.f('ix_time_block_activities_sequence_order'), table_name='time_block_activities')
    op.drop_index(op.f('ix_time_block_activities_id'), table_name='time_block_activities')
    op.drop_table('time_block_activities')
    # ### end Alembic commands ###
