"""add_is_archived_to_students

Revision ID: 8f054481089d
Revises: 7807dc6ddd5b
Create Date: 2025-08-10 23:48:02.447763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f054481089d'
down_revision: Union[str, None] = '7807dc6ddd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    op.create_index(op.f('ix_students_is_archived'), 'students', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_is_archived'), table_name='students')
    op.drop_column('students', 'is_archived')
    # ### end Alembic commands ###
