"""Add scheduling tables - appointments, time blocks, block assignments

Revision ID: d5797daff9d2
Revises: 679c23df944a
Create Date: 2025-08-09 08:59:29.070023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5797daff9d2'
down_revision: Union[str, None] = '679c23df944a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip column comment updates due to SQL Server DDL compiler issue
    # op.alter_column('goal_objectives', 'objective_number',
    #            existing_type=sa.INTEGER(),
    #            comment='Objective sequence number (1-10)',
    #            existing_comment='Objective sequence number (1-4)',
    #            existing_nullable=False)
    # op.alter_column('students', 'school_id',
    #            existing_type=sa.INTEGER(),
    #            comment='Students current school',
    #            existing_nullable=True)
    
    # Create appointments table
    op.create_table('appointments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=True),
        sa.Column('school_id', sa.Integer(), nullable=True),
        sa.Column('start_datetime', sa.DateTime(), nullable=False),
        sa.Column('end_datetime', sa.DateTime(), nullable=False),
        sa.Column('appointment_type', sa.String(length=50), server_default='individual', nullable=False),
        sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('therapy_session_completed', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('session_notes', sa.Text(), nullable=True),
        sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_type'), 'appointments', ['appointment_type'], unique=False)
    op.create_index(op.f('ix_appointments_end_datetime'), 'appointments', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_school_id'), 'appointments', ['school_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_datetime'), 'appointments', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_student_id'), 'appointments', ['student_id'], unique=False)
    op.create_index(op.f('ix_appointments_teacher_id'), 'appointments', ['teacher_id'], unique=False)

    # Create time_blocks table
    op.create_table('time_blocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=True),
        sa.Column('school_id', sa.Integer(), nullable=True),
        sa.Column('start_datetime', sa.DateTime(), nullable=False),
        sa.Column('end_datetime', sa.DateTime(), nullable=False),
        sa.Column('block_type', sa.String(length=50), server_default='group_therapy', nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('max_students', sa.Integer(), nullable=True),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
        sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_blocks_block_type'), 'time_blocks', ['block_type'], unique=False)
    op.create_index(op.f('ix_time_blocks_end_datetime'), 'time_blocks', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_time_blocks_id'), 'time_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_time_blocks_school_id'), 'time_blocks', ['school_id'], unique=False)
    op.create_index(op.f('ix_time_blocks_start_datetime'), 'time_blocks', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_time_blocks_status'), 'time_blocks', ['status'], unique=False)
    op.create_index(op.f('ix_time_blocks_teacher_id'), 'time_blocks', ['teacher_id'], unique=False)

    # Create block_assignments table
    op.create_table('block_assignments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time_block_id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='assigned', nullable=False),
        sa.Column('assignment_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('removed_date', sa.DateTime(), nullable=True),
        sa.Column('created_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('modified_date', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['time_block_id'], ['time_blocks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_assignments_id'), 'block_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_block_assignments_status'), 'block_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_block_assignments_student_id'), 'block_assignments', ['student_id'], unique=False)
    op.create_index(op.f('ix_block_assignments_time_block_id'), 'block_assignments', ['time_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop block_assignments table
    op.drop_index(op.f('ix_block_assignments_time_block_id'), table_name='block_assignments')
    op.drop_index(op.f('ix_block_assignments_student_id'), table_name='block_assignments')
    op.drop_index(op.f('ix_block_assignments_status'), table_name='block_assignments')
    op.drop_index(op.f('ix_block_assignments_id'), table_name='block_assignments')
    op.drop_table('block_assignments')

    # Drop time_blocks table
    op.drop_index(op.f('ix_time_blocks_teacher_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_status'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_start_datetime'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_school_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_end_datetime'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_block_type'), table_name='time_blocks')
    op.drop_table('time_blocks')

    # Drop appointments table
    op.drop_index(op.f('ix_appointments_teacher_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_student_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_datetime'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_school_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_end_datetime'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_type'), table_name='appointments')
    op.drop_table('appointments')
    
    # Skip column comment updates due to SQL Server DDL compiler issue
    # op.alter_column('students', 'school_id',
    #            existing_type=sa.INTEGER(),
    #            comment=None,
    #            existing_comment='Students current school',
    #            existing_nullable=True)
    # op.alter_column('goal_objectives', 'objective_number',
    #            existing_type=sa.INTEGER(),
    #            comment='Objective sequence number (1-4)',
    #            existing_comment='Objective sequence number (1-10)',
    #            existing_nullable=False)
    # ### end Alembic commands ###
